/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.mydsl1;

import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.eclipse.xtext.scoping.IScopeProvider;
import org.xtext.example.mydsl1.scoping.MyDslScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {
	
	public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider(){
		return MyRobotDSLQNP.class;
	}
	
}
