/*
 * generated by Xtext 2.34.0
 */
package org.xtext.example.mydsl1.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.mydsl1.ide.contentassist.antlr.internal.InternalMyDslParser;
import org.xtext.example.mydsl1.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MyDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MyDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getRobotModelAccess().getAlternatives_1(), "rule__RobotModel__Alternatives_1");
			builder.put(grammarAccess.getExpressionAccess().getAlternatives(), "rule__Expression__Alternatives");
			builder.put(grammarAccess.getEqualityAccess().getOperationAlternatives_1_1_0(), "rule__Equality__OperationAlternatives_1_1_0");
			builder.put(grammarAccess.getComparisonAccess().getOperationAlternatives_1_1_0(), "rule__Comparison__OperationAlternatives_1_1_0");
			builder.put(grammarAccess.getPlusOrMinusAccess().getOperationAlternatives_1_0_1_0(), "rule__PlusOrMinus__OperationAlternatives_1_0_1_0");
			builder.put(grammarAccess.getMultOrDivAccess().getOperationAlternatives_1_1_0(), "rule__MultOrDiv__OperationAlternatives_1_1_0");
			builder.put(grammarAccess.getPrimaryAccess().getAlternatives(), "rule__Primary__Alternatives");
			builder.put(grammarAccess.getAtomicAccess().getAlternatives_1(), "rule__Atomic__Alternatives_1");
			builder.put(grammarAccess.getAtomicAccess().getAlternatives_1_1(), "rule__Atomic__Alternatives_1_1");
			builder.put(grammarAccess.getConditionAccess().getAlternatives(), "rule__Condition__Alternatives");
			builder.put(grammarAccess.getActionAccess().getAlternatives(), "rule__Action__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getDurationAccess().getAlternatives(), "rule__Duration__Alternatives");
			builder.put(grammarAccess.getLightPosAccess().getAlternatives(), "rule__LightPos__Alternatives");
			builder.put(grammarAccess.getButtonTypeAccess().getAlternatives(), "rule__ButtonType__Alternatives");
			builder.put(grammarAccess.getRobotModelAccess().getGroup(), "rule__RobotModel__Group__0");
			builder.put(grammarAccess.getRobotModelAccess().getGroup_1_1(), "rule__RobotModel__Group_1_1__0");
			builder.put(grammarAccess.getRobotModelAccess().getGroup_1_1_3(), "rule__RobotModel__Group_1_1_3__0");
			builder.put(grammarAccess.getRobotModelAccess().getGroup_1_2(), "rule__RobotModel__Group_1_2__0");
			builder.put(grammarAccess.getRobotModelAccess().getGroup_1_2_3(), "rule__RobotModel__Group_1_2_3__0");
			builder.put(grammarAccess.getOrAccess().getGroup(), "rule__Or__Group__0");
			builder.put(grammarAccess.getOrAccess().getGroup_1(), "rule__Or__Group_1__0");
			builder.put(grammarAccess.getAndAccess().getGroup(), "rule__And__Group__0");
			builder.put(grammarAccess.getAndAccess().getGroup_1(), "rule__And__Group_1__0");
			builder.put(grammarAccess.getEqualityAccess().getGroup(), "rule__Equality__Group__0");
			builder.put(grammarAccess.getEqualityAccess().getGroup_1(), "rule__Equality__Group_1__0");
			builder.put(grammarAccess.getComparisonAccess().getGroup(), "rule__Comparison__Group__0");
			builder.put(grammarAccess.getComparisonAccess().getGroup_1(), "rule__Comparison__Group_1__0");
			builder.put(grammarAccess.getIfAccess().getGroup(), "rule__If__Group__0");
			builder.put(grammarAccess.getThenAccess().getGroup(), "rule__Then__Group__0");
			builder.put(grammarAccess.getElseAccess().getGroup(), "rule__Else__Group__0");
			builder.put(grammarAccess.getPlusOrMinusAccess().getGroup(), "rule__PlusOrMinus__Group__0");
			builder.put(grammarAccess.getPlusOrMinusAccess().getGroup_1(), "rule__PlusOrMinus__Group_1__0");
			builder.put(grammarAccess.getPlusOrMinusAccess().getGroup_1_0(), "rule__PlusOrMinus__Group_1_0__0");
			builder.put(grammarAccess.getMultOrDivAccess().getGroup(), "rule__MultOrDiv__Group__0");
			builder.put(grammarAccess.getMultOrDivAccess().getGroup_1(), "rule__MultOrDiv__Group_1__0");
			builder.put(grammarAccess.getPrimaryAccess().getGroup_0(), "rule__Primary__Group_0__0");
			builder.put(grammarAccess.getPrimaryAccess().getGroup_1(), "rule__Primary__Group_1__0");
			builder.put(grammarAccess.getAtomicAccess().getGroup(), "rule__Atomic__Group__0");
			builder.put(grammarAccess.getEventAccess().getGroup(), "rule__Event__Group__0");
			builder.put(grammarAccess.getEventAccess().getGroup_3(), "rule__Event__Group_3__0");
			builder.put(grammarAccess.getEventAccess().getGroup_4(), "rule__Event__Group_4__0");
			builder.put(grammarAccess.getEventAccess().getGroup_4_2(), "rule__Event__Group_4_2__0");
			builder.put(grammarAccess.getSoundAccess().getGroup(), "rule__Sound__Group__0");
			builder.put(grammarAccess.getButtonAccess().getGroup(), "rule__Button__Group__0");
			builder.put(grammarAccess.getSensorAccess().getGroup(), "rule__Sensor__Group__0");
			builder.put(grammarAccess.getTapAccess().getGroup(), "rule__Tap__Group__0");
			builder.put(grammarAccess.getMotorActionAccess().getGroup(), "rule__MotorAction__Group__0");
			builder.put(grammarAccess.getMotorActionAccess().getGroup_3(), "rule__MotorAction__Group_3__0");
			builder.put(grammarAccess.getMotorActionAccess().getGroup_4(), "rule__MotorAction__Group_4__0");
			builder.put(grammarAccess.getSoundActionAccess().getGroup(), "rule__SoundAction__Group__0");
			builder.put(grammarAccess.getSoundActionAccess().getGroup_3(), "rule__SoundAction__Group_3__0");
			builder.put(grammarAccess.getSoundActionAccess().getGroup_3_2(), "rule__SoundAction__Group_3_2__0");
			builder.put(grammarAccess.getLightActionAccess().getGroup(), "rule__LightAction__Group__0");
			builder.put(grammarAccess.getLightActionAccess().getGroup_5(), "rule__LightAction__Group_5__0");
			builder.put(grammarAccess.getLightActionAccess().getGroup_6(), "rule__LightAction__Group_6__0");
			builder.put(grammarAccess.getLightActionAccess().getGroup_7(), "rule__LightAction__Group_7__0");
			builder.put(grammarAccess.getMusicSettingAccess().getGroup(), "rule__MusicSetting__Group__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getRobotModelAccess().getEventsAssignment_1_0(), "rule__RobotModel__EventsAssignment_1_0");
			builder.put(grammarAccess.getRobotModelAccess().getActionsAssignment_1_1_2(), "rule__RobotModel__ActionsAssignment_1_1_2");
			builder.put(grammarAccess.getRobotModelAccess().getActionsAssignment_1_1_3_1(), "rule__RobotModel__ActionsAssignment_1_1_3_1");
			builder.put(grammarAccess.getRobotModelAccess().getConditionsAssignment_1_2_2(), "rule__RobotModel__ConditionsAssignment_1_2_2");
			builder.put(grammarAccess.getRobotModelAccess().getConditionsAssignment_1_2_3_1(), "rule__RobotModel__ConditionsAssignment_1_2_3_1");
			builder.put(grammarAccess.getRobotModelAccess().getExpressionsAssignment_1_3(), "rule__RobotModel__ExpressionsAssignment_1_3");
			builder.put(grammarAccess.getOrAccess().getOperationAssignment_1_1(), "rule__Or__OperationAssignment_1_1");
			builder.put(grammarAccess.getOrAccess().getRightAssignment_1_2(), "rule__Or__RightAssignment_1_2");
			builder.put(grammarAccess.getAndAccess().getOperationAssignment_1_1(), "rule__And__OperationAssignment_1_1");
			builder.put(grammarAccess.getAndAccess().getRightAssignment_1_2(), "rule__And__RightAssignment_1_2");
			builder.put(grammarAccess.getEqualityAccess().getOperationAssignment_1_1(), "rule__Equality__OperationAssignment_1_1");
			builder.put(grammarAccess.getEqualityAccess().getRightAssignment_1_2(), "rule__Equality__RightAssignment_1_2");
			builder.put(grammarAccess.getComparisonAccess().getOperationAssignment_1_1(), "rule__Comparison__OperationAssignment_1_1");
			builder.put(grammarAccess.getComparisonAccess().getRightAssignment_1_2(), "rule__Comparison__RightAssignment_1_2");
			builder.put(grammarAccess.getIfAccess().getOperationAssignment_1(), "rule__If__OperationAssignment_1");
			builder.put(grammarAccess.getIfAccess().getLeftAssignment_2(), "rule__If__LeftAssignment_2");
			builder.put(grammarAccess.getIfAccess().getRightAssignment_3(), "rule__If__RightAssignment_3");
			builder.put(grammarAccess.getThenAccess().getOperationAssignment_1(), "rule__Then__OperationAssignment_1");
			builder.put(grammarAccess.getThenAccess().getLeftAssignment_2(), "rule__Then__LeftAssignment_2");
			builder.put(grammarAccess.getThenAccess().getRightAssignment_3(), "rule__Then__RightAssignment_3");
			builder.put(grammarAccess.getElseAccess().getOperationAssignment_1(), "rule__Else__OperationAssignment_1");
			builder.put(grammarAccess.getElseAccess().getLeftAssignment_2(), "rule__Else__LeftAssignment_2");
			builder.put(grammarAccess.getPlusOrMinusAccess().getOperationAssignment_1_0_1(), "rule__PlusOrMinus__OperationAssignment_1_0_1");
			builder.put(grammarAccess.getPlusOrMinusAccess().getRightAssignment_1_1(), "rule__PlusOrMinus__RightAssignment_1_1");
			builder.put(grammarAccess.getMultOrDivAccess().getOperationAssignment_1_1(), "rule__MultOrDiv__OperationAssignment_1_1");
			builder.put(grammarAccess.getMultOrDivAccess().getRightAssignment_1_2(), "rule__MultOrDiv__RightAssignment_1_2");
			builder.put(grammarAccess.getPrimaryAccess().getOperationAssignment_1_1(), "rule__Primary__OperationAssignment_1_1");
			builder.put(grammarAccess.getPrimaryAccess().getLeftAssignment_1_2(), "rule__Primary__LeftAssignment_1_2");
			builder.put(grammarAccess.getAtomicAccess().getValueAssignment_1_0(), "rule__Atomic__ValueAssignment_1_0");
			builder.put(grammarAccess.getEventAccess().getNameAssignment_2(), "rule__Event__NameAssignment_2");
			builder.put(grammarAccess.getEventAccess().getConditionAssignment_3_1(), "rule__Event__ConditionAssignment_3_1");
			builder.put(grammarAccess.getEventAccess().getActionsAssignment_4_1(), "rule__Event__ActionsAssignment_4_1");
			builder.put(grammarAccess.getEventAccess().getActionsAssignment_4_2_1(), "rule__Event__ActionsAssignment_4_2_1");
			builder.put(grammarAccess.getSoundAccess().getConditionnameAssignment_2(), "rule__Sound__ConditionnameAssignment_2");
			builder.put(grammarAccess.getButtonAccess().getConditionnameAssignment_2(), "rule__Button__ConditionnameAssignment_2");
			builder.put(grammarAccess.getButtonAccess().getButtonAssignment_4(), "rule__Button__ButtonAssignment_4");
			builder.put(grammarAccess.getSensorAccess().getConditionnameAssignment_2(), "rule__Sensor__ConditionnameAssignment_2");
			builder.put(grammarAccess.getSensorAccess().getSensorPosAssignment_4(), "rule__Sensor__SensorPosAssignment_4");
			builder.put(grammarAccess.getTapAccess().getConditionnameAssignment_2(), "rule__Tap__ConditionnameAssignment_2");
			builder.put(grammarAccess.getMotorActionAccess().getActionnameAssignment_2(), "rule__MotorAction__ActionnameAssignment_2");
			builder.put(grammarAccess.getMotorActionAccess().getMotorLeftAssignment_3_1(), "rule__MotorAction__MotorLeftAssignment_3_1");
			builder.put(grammarAccess.getMotorActionAccess().getMotorRightAssignment_4_1(), "rule__MotorAction__MotorRightAssignment_4_1");
			builder.put(grammarAccess.getSoundActionAccess().getActionnameAssignment_2(), "rule__SoundAction__ActionnameAssignment_2");
			builder.put(grammarAccess.getSoundActionAccess().getMusicsettingsAssignment_3_1(), "rule__SoundAction__MusicsettingsAssignment_3_1");
			builder.put(grammarAccess.getSoundActionAccess().getMusicsettingsAssignment_3_2_1(), "rule__SoundAction__MusicsettingsAssignment_3_2_1");
			builder.put(grammarAccess.getLightActionAccess().getActionnameAssignment_2(), "rule__LightAction__ActionnameAssignment_2");
			builder.put(grammarAccess.getLightActionAccess().getPosAssignment_4(), "rule__LightAction__PosAssignment_4");
			builder.put(grammarAccess.getLightActionAccess().getRedAssignment_5_1(), "rule__LightAction__RedAssignment_5_1");
			builder.put(grammarAccess.getLightActionAccess().getGreenAssignment_6_1(), "rule__LightAction__GreenAssignment_6_1");
			builder.put(grammarAccess.getLightActionAccess().getBlueAssignment_7_1(), "rule__LightAction__BlueAssignment_7_1");
			builder.put(grammarAccess.getMusicSettingAccess().getNoteAssignment_1(), "rule__MusicSetting__NoteAssignment_1");
			builder.put(grammarAccess.getMusicSettingAccess().getDurationAssignment_3(), "rule__MusicSetting__DurationAssignment_3");
			builder.put(grammarAccess.getMusicSettingAccess().getPosAssignment_5(), "rule__MusicSetting__PosAssignment_5");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MyDslGrammarAccess grammarAccess;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
